### ISSUE TITLE
Undefined client

### ISSUE THREAD

**Issue by jki123** [jyap808/go-poloniex#7]
Tried to get candle-data from "poloniex.go"-example by uncommenting the relevant code-lines. Got the error-message
./poloniex.go:55: undefined: client in client.ChartData

Do you have any hints for me :-(

Best regards 
Joerg

**Comment by jyap808** [comment]
Hmm, someone else added a pull request for that feature so if you fix it you can put in a pull request.

Closing for now since I haven't tried that feature.
